import type { NextPage } from 'next'
import Head from 'next/head'
import { NewGameSettings } from '../../src/components/NewGameSettings'
import { GameMode } from '../../src/components/GameMode'
import styled from 'styled-components'


const Container = styled.div`

`


const Game: NextPage = () => {

  function selectNumOfPlayers () {
      console.log('two')
  }


  return (
    <Container>
      <Head>
        <title>Frodle - New Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <GameMode />
      </main>
    </Container>
  )
}

export default Game
