import type { NextPage } from 'next'
import Head from 'next/head'
import { GameMode } from '../../src/components/GameMode'
import styled from 'styled-components'
import { useGetActiveRooms, useInsertRoom } from '../../src/hooks/rooms'
import { v4 as uuidv4 } from 'uuid'
import { useRouter } from 'next/router'

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`

const Game: NextPage = () => {
  const { rooms } = useGetActiveRooms()
  const { insertRoom, error, loading } = useInsertRoom()
  const router = useRouter()
  const roomId = uuidv4()

  function createRoom() {
    insertRoom({
      hostId: "78ad3bbf-7d76-4580-824c-e031abdb7da7",
      id: roomId
    }).then(() => router.push(`/Game/${roomId}`))
  }

  function joinRoom() {
    // add ability to join rooms
  }

  return (
    <Container>
      <Head>
        <title>Frodle - New Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameMode createRoom={createRoom} joinRoom={joinRoom} />
    </Container>
  )
}

export default Game
