import type { NextPage } from 'next'
import Head from 'next/head'
import { GameMode } from '../../src/components/GameMode'
import styled from 'styled-components'


const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`


const Game: NextPage = () => {

  function createRoom () {
      console.log('creating room')
  }

  function joinRoom () {
      console.log('joining room')
  }


  return (
    <Container>
      <Head>
        <title>Frodle - New Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameMode createRoom={createRoom} joinRoom={joinRoom} />
    </Container>
  )
}

export default Game
