import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../src/layout/layout";
import { GameConsumer, GameProvider, GameContext } from "../src/providers/game";
import { Game } from "../src/Game/Game";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Neno</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons8-n-32.png" />
      </Head>
      <GameProvider>
        <GameConsumer>
          {(value) => <Game context={value} />}
        </GameConsumer>
      </GameProvider>
    </Layout>
  );
};

export async function getServerSideProps(_context: any) {
  return {
    props: {}, // Will be passed to the page component as props
  };
}

export default Home;
