import React from "react";
import Head from 'next/head'
import styled from 'styled-components'
import { useRouter } from "next/router";
import Navbar from "../components/ui/navbar";

const Main = styled.section`
    background: red;
  padding: 1rem;
  margin: 0;
  background: var(--grey-background);
  height: 100vh;
`

export default function Layout({ children }: any) {
    const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
          <nav>
              <Navbar />
          </nav>
      </header>
      <Main>
      {children}
      </Main>
    </>
  )
}